services:
  - type: worker
    name: telegram-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ai-pipeline.py"
    pythonVersion: 3.11
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_KEY
        sync: false
